### ISSUE TITLE
Sensiolab is not available anymore

### ISSUE THREAD

**Issue by bedo2991** [ohdearapp/gitlab-ci-pipeline-for-laravel#11]
More infos: [https://github.com/sensiolabs/security-checker](url)

**Comment by RossUK88** [comment]
My workaround is to replace the scripts with this:
```
script:
    - curl -L -sS --output local-php-security-checker https://github.com/fabpot/local-php-security-checker/releases/download/v1.0.0/local-php-security-checker_1.0.0_linux_amd64
    - chmod +x ./local-php-security-checker
    - ./local-php-security-checker
```
    
Not the best because of targeting a specific release, I tried to use the symfony cli docker image, but as gitlab runner doesn't have shell installed as default you end up needing to create a custom docker image. But this works for now until I get that into the pipeline

**Comment by paras-malhotra** [comment]
You can use the [Enlightn Security Checker](https://github.com/enlightn/security-checker) instead. Just need to change the Github link in the yml file.

**Comment by byhlz** [comment]
Could be a duplicate of #10

**Comment by mattiasgeniar** [comment]
Hi all,

We've long migrated away from Gitlab CI and haven't been able to support this repo as well as we should have. We'll be archiving this and putting it in read-only mode, anyone that's willing to further maintain the code is free to fork this to their own version.

Thanks for the contributions & discussions from all involved!

Mattias
